CP_2 - Deep Learning

Sibele Tatiana Gon√ßalves do Amaral

In [261]:
import pandas as pd
df = pd.read_csv('/home/gym_members_exercise_tracking.csv')
df.head(5)

,Age,Gender,Weight (kg),Height (m),Max_BPM,Avg_BPM,Resting_BPM,Session_Duration (hours),Calories_Burned,Workout_Type,Fat_Percentage,Water_Intake (liters),Workout_Frequency (days/week),Experience_Level,BMI
0,56,Male,88.3,1.71,180,157,60,1.69,1313.0,Yoga,12.6,3.5,4,3,30.20
1,46,Female,74.9,1.53,179,151,66,1.30,883.0,HIIT,33.9,2.1,4,2,32.00
2,32,Female,68.1,1.66,167,122,54,1.11,677.0,Cardio,33.4,2.3,4,2,24.71
3,25,Male,53.2,1.70,190,164,56,0.59,532.0,Strength,28.8,2.1,3,1,18.41
4,38,Male,46.1,1.79,188,158,68,0.64,556.0,Strength,29.2,2.8,3,1,14.39

In [262]:
df1=df.copy()

In [285]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

from sklearn.neural_network import MLPRegressor
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import r2_score
from sklearn.preprocessing import StandardScaler

print(df.shape)
df.head(5)

df['Workout_Type'].value_counts()

(973, 15)

Workout_Type
Strength    258
Cardio      255
Yoga        239
HIIT        221
Name: count, dtype: int64

In [264]:
df1.dtypes

Age                                int64
Gender                            object
Weight (kg)                      float64
Height (m)                       float64
Max_BPM                            int64
Avg_BPM                            int64
Resting_BPM                        int64
Session_Duration (hours)         float64
Calories_Burned                  float64
Workout_Type                      object
Fat_Percentage                   float64
Water_Intake (liters)            float64
Workout_Frequency (days/week)      int64
Experience_Level                   int64
BMI                              float64
dtype: object

In [287]:
df1 = df.copy()
df1['class1'] = df.apply( lambda row: 1 if row['Workout_Type']=='Yoga' else 0 , axis=1)
df1['class2'] = df.apply( lambda row: 1 if row['Workout_Type']=='HIIT' else 0 , axis=1)
df1['class3'] = df.apply( lambda row: 1 if row['Workout_Type']=='Strength' else 0 , axis=1)
df1['class4'] = df.apply( lambda row: 1 if row['Workout_Type']=='Other' else 0 , axis=1)
df1['Gender'] = df.apply( lambda row: 1 if row['Gender']=='Male' else 0 , axis=1)

del df1['Workout_Type']
df1.head(5)

,Age,Gender,Weight (kg),Height (m),Max_BPM,Avg_BPM,Resting_BPM,Session_Duration (hours),Calories_Burned,Fat_Percentage,Water_Intake (liters),Workout_Frequency (days/week),Experience_Level,BMI,class1,class2,class3,class4
0,56,1,88.3,1.71,180,157,60,1.69,1313.0,12.6,3.5,4,3,30.20,1,0,0,0
1,46,0,74.9,1.53,179,151,66,1.30,883.0,33.9,2.1,4,2,32.00,0,1,0,0
2,32,0,68.1,1.66,167,122,54,1.11,677.0,33.4,2.3,4,2,24.71,0,0,0,0
3,25,1,53.2,1.70,190,164,56,0.59,532.0,28.8,2.1,3,1,18.41,0,0,1,0
4,38,1,46.1,1.79,188,158,68,0.64,556.0,29.2,2.8,3,1,14.39,0,0,1,0

In [267]:
print(len(df1))
print(df1['Experience_Level'].value_counts())

973
Experience_Level
2    406
1    376
3    191
Name: count, dtype: int64

In [268]:
df1.dtypes

Age                                int64
Weight (kg)                      float64
Height (m)                       float64
Max_BPM                            int64
Avg_BPM                            int64
Resting_BPM                        int64
Session_Duration (hours)         float64
Calories_Burned                  float64
Fat_Percentage                   float64
Water_Intake (liters)            float64
Workout_Frequency (days/week)      int64
Experience_Level                   int64
BMI                              float64
class1                             int64
class2                             int64
class3                             int64
class4                             int64
dtype: object

In [322]:
df1_1 = df1[df1['Experience_Level']==1].sample(3000, replace=True, random_state=1)
df1_2 = df1[df1['Experience_Level']==2].sample(3000, replace=True, random_state=1)
df1_3 = df1[df1['Experience_Level']==3].sample(3000, replace=True, random_state=1)
df2 = pd.concat([df1_1, df1_2, df1_3])

In [323]:
x = df2[['Age',
         'Gender',
 'Weight (kg)',
 'Height (m)',
 'Max_BPM',
 'Avg_BPM',
 'Resting_BPM',
 'Session_Duration (hours)',
 'Calories_Burned',
 'Fat_Percentage',
 'Water_Intake (liters)',
 'Workout_Frequency (days/week)',
 'BMI',
 'class1',
 'class2',
 'class3',
 'class4']]
y = df2[['Experience_Level']]
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.50, random_state=42)

ss = StandardScaler()
x_train_scaled = ss.fit_transform(x_train)
x_test_scaled = ss.transform(x_test)

nn = MLPClassifier(random_state=42,max_iter=1500,
                          hidden_layer_sizes=(20,20,20),
                          activation = 'relu',
                          alpha = 0.005,
                          solver = 'adam')
nn.fit(x_train_scaled, y_train.values.ravel())

y_test_pred_nn = nn.predict(x_test_scaled)
y_train_pred_nn = nn.predict(x_train_scaled)

print(r2_score(y_train, y_train_pred_nn))
print(r2_score(y_test, y_test_pred_nn))

1.0
0.9979881151254175

In [353]:
x = df1[['Age',
 'Gender',
 'Weight (kg)',
 'Height (m)',
 'Max_BPM',
 'Resting_BPM',
 'Session_Duration (hours)',
 'Calories_Burned',
 'Fat_Percentage',
 'Water_Intake (liters)',
 'Workout_Frequency (days/week)',
 'BMI',
 'Experience_Level',
 'class1',
 'class2',
 'class3',
 'class4']]
y = df1[['Avg_BPM']] # TENHO QUE USAR UM REGRESSOR!!!!!

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.8, random_state=42)

ss = StandardScaler()
x_train_scaled = ss.fit_transform(x_train)
x_test_scaled = ss.transform(x_test)

model = MLPRegressor(random_state=42, max_iter=1900, hidden_layer_sizes=(110,100,110), activation='relu', solver='adam',alpha=0.001)
model.fit(x_train_scaled, y_train)

y_train_pred = model.predict(x_train_scaled)
y_test_pred = model.predict(x_test_scaled)

print(r2_score(y_train, y_train_pred))
print(r2_score(y_test, y_test_pred))

/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:1631: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

0.9981638518007888
0.2552456991050559